// Curated banks for hangman / chain / trivia / riddle.
// Keep this file data-only so game logic stays readable.

export const HANGMAN = {
    animals: ['elephant', 'giraffe', 'penguin', 'dolphin', 'cheetah', 'octopus', 'kangaroo', 'butterfly', 'crocodile', 'flamingo', 'leopard', 'buffalo', 'gorilla', 'hamster', 'peacock'],
    food: ['pizza', 'hamburger', 'pineapple', 'chocolate', 'spaghetti', 'avocado', 'pancake', 'popcorn', 'sandwich', 'coconut', 'plantain', 'jollof', 'suya', 'noodles', 'banana'],
    places: ['lagos', 'london', 'paris', 'tokyo', 'canada', 'nigeria', 'egypt', 'brazil', 'kenya', 'morocco', 'accra', 'ibadan', 'dubai', 'madrid', 'nairobi'],
    tech: ['javascript', 'whatsapp', 'internet', 'keyboard', 'android', 'bluetooth', 'computer', 'database', 'algorithm', 'browser', 'software', 'network', 'password', 'download', 'charger'],
    random: ['eclipse', 'phantom', 'eventide', 'thunder', 'rainbow', 'treasure', 'diamond', 'whisper', 'galaxy', 'umbrella', 'festival', 'midnight', 'pyramid', 'lantern', 'horizon']
};

export const CHAIN_STARTERS = ['apple', 'elephant', 'table', 'water', 'music', 'river', 'orange', 'phone', 'sun', 'dream', 'light', 'house', 'night', 'fire'];

// Compact common-word dictionary for word chain (lowercase a-z, 3+ letters).
export const CHAIN_WORDS = new Set(`
able about above abuse academy accent accept access accident account accuse ache acid across act actor actual add address adult advice advise affair afford afraid after again age agent ago agree ahead aid aim air airport alarm album alcohol alive all alley allow almost alone along already also always amazing among amount ancient and anger angle angry animal ankle announce annual another answer any anybody anyone anything anyway apart apartment ape apologize appear apple apply april area argue arm armed army around arrange arrest arrive arrow art artist as ash aside ask asleep assault assist assume athlete atmosphere attach attack attend attention attic audience aunt author auto autumn available average avoid awake award aware away awesome awful
baby back background backyard bacon bad badge bag bake baker balance ball balloon banana band bank bar bare bargain bark barn barrel base baseball basic basket bat bath bathroom battle bay beach bean bear beard beast beat beautiful beauty because become bed bee beef been beer before beg begin behave behind being belief believe bell belong below belt bench bend benefit berry beside best bet better between beyond bible bicycle big bike bill billion bird birth birthday bit bite bitter black blade blame blank blanket blast blind block blood blow blue board boat body boil bomb bond bone bonus book boom boot border born borrow boss both bottle bottom bowl box boy brain branch brand brave bread break breakfast breast breath breathe brick bridge brief bright bring broad broken brother brown brush bubble bucket buddy budget buffalo build bulb bulk bullet bunch bundle burden burn burst bury bus bush business busy but butter button buy buyer
cab cabin cable cafe cage cake calculate calendar call calm camera camp campaign campus can canal cancel cancer candidate candle candy canvas cap capable capital captain capture car card care career careful cargo carpet carry cart cartoon carve case cash casino cast castle cat catch category cattle cause cave cease ceiling celebrate cell cement cemetery census cent center century cereal ceremony certain chain chair chalk challenge chamber champion chance change channel chaos chapter charge charm chart chase cheap cheat check cheek cheese chef chemical chest chicken chief child childhood chin chip chocolate choice choose church cigarette circle citizen city civil claim clap class classic classroom clay clean clear clerk clever click client cliff climate climb clock close cloth cloud club clue coach coal coast coat code coffee coil coin cold collar collect college color column comb come comedy comfort comic coming command comment commercial commission commit common community company compare compete complain complete complex computer concern concert conclude condition conduct conference confess confidence confirm conflict confuse connect consider consist constant construct consult contain content contest continue contract control convert cook cookie cool copy corner correct cost cotton couch could count country couple courage course court cousin cover cow cozy crack craft crash crazy cream create creature credit crew crime criminal crisis critic crop cross crowd crown cruel crush cry crystal cub cube cucumber cue cup cupboard cure curious curl current curtain curve cushion custom cut cute cycle
dad daily dam damage damp dance danger dangerous dare dark dash data date daughter dawn day dead deaf deal dear death debate debt decade decide decision deck declare deep deer defeat defend defense define degree delay delicate delight deliver demand den dentist deny depend depth describe desert design desire desk destroy detail detect develop device devil diamond diary did die diet difference different difficult dig dim dine dinner dip direct dirt dirty disappear disaster discipline discover discuss disease dish disk display distance district dive divide divorce do doctor document dog doll dollar dolphin donate donkey door double doubt dough down dozen draft drag dragon drain drama drastic draw drawer dream dress dried drink drive driver drop drug drum dry duck due dug dull dump during dust duty
each eager ear early earn earth ease east easy eat echo edge edit educate egg ego eight either elbow elder elect electric elegant element elephant elevator else email embarrass emerge emotion emperor employ empty enable end enemy energy engine enjoy enough enter entire entrance entry envelope envy equal equator era error escape especially essay establish estate estimate even evening event ever every everybody everyone everything evidence evil exact exam examine example exceed excellent except exchange excite excuse exercise exist exit expand expect expense expensive expert explain explode explore extra eye
face fact factor factory fail failure fair faith fall false fame family famous fan fancy far farm farmer fashion fast fat fate father fault favor favorite fear feast feather feature fed federal fee feed feel fellow female fence festival fever few fiber field fierce fifteen fifth fifty fight figure file fill film final finally finance find fine finger finish fire firm first fish fist fit five fix flag flame flash flat flavor flee flesh flight flip float flock flood floor flour flow flower flu fly foam focus fog fold folk follow food fool foot football for force forest forever forget fork form formal former fort fortune forty forum forward fossil foster found four fourth fox frame free freedom freeze french frequent fresh friday friend friendly friendship frog from front frost frozen fruit fry fuel full fun funeral funny fur furnace furniture further future
gadget gain galaxy gallery game gang gap garage garden garlic gas gate gather gauge gave gay gear geese gender gene general generate generous genius gentle gentleman genuine geography germ gesture get ghost giant gift giggle ginger giraffe girl give glad glance glass glide globe glory glove glow glue goal goat god gold golden golf gone good goodbye goose gorgeous gorilla gospel gossip got govern grab grade grain grand grandfather grandmother grant grape graph grass grateful grave gravity gray great green greet grew grey grief grill grim grin grind grip grocery groom gross ground group grow grown growth guarantee guard guess guest guide guilt guilty guitar gum gun guy gym
habit had hair half hall ham hammer hand handle hang happen happy harbor hard hardly hardware harm hat hate have hawk hay he head headache health healthy heap hear heart heat heaven heavy heel height held helicopter hell hello help hen her here hero hers herself hey hidden hide high highway hill him himself hip hire his history hit hobby hockey hold hole holiday hollow holy home homework honest honey honor hook hop hope horn horse hospital host hot hotel hour house household how however hug huge human humor hundred hungry hunt hunter hurricane hurry hurt husband hut
ice idea ideal identify identity idiot idle if ignore ill illegal illness image imagine impact important impose impress improve in inch include income increase indeed independent index indoor industry infant influence info inform information injure injury ink inner innocent input insect inside insist inspect inspire install instance instant instead insult insurance intelligence intend interest interior international internet interview into introduce invent invention invest invitation invite involve iron island issue it item its itself ivory
jacket jail jam january jar jaw jazz jealous jeans jelly jerk jet jewel jewelry job join joint joke journal journey joy judge juice july jump june jungle junior junk jury just justice
keep keeper kept key kick kid kidnap kidney kill kilo kilometer kind king kingdom kiss kit kitchen kite kitten knee knew knife knight knit knob knock knot know known
lab label labor lack ladder lady lake lamb lamp land lane language lantern lap large last late later latest laugh launch law lawn lawyer lay layer lazy lead leader leaf league leak lean leap learn least leather leave lecture left leg legal lemon lend length lens less lesson let letter level liar liberty library license lid lie life lift light like likely limb lime limit line link lion lip liquid list listen little live liver living lizard load loaf loan lobby local lock log logic lonely long look loop loose lord lose loss lost lot loud love lovely lover low loyal luck lucky luggage lunch lung luxury
machine mad magazine magic magnet maid mail main major make male mall mama man manage manager manner many map marble march mark market marriage married marry mass master match mate material math matter may maybe mayor maze meal mean meaning meanwhile measure meat mechanic medal media medical medicine medium meet meeting melt member memory men mental mention menu mercy mere merge merit merry mess message metal method middle midnight might mile military milk mill million mind mine mineral minister minor minute mirror miss mission mistake mix mixture mobile model modern modest mom moment monday money monkey month mood moon moral more morning mortgage most mother motion motor mountain mouse mouth move movie much mud mug multiple murder muscle museum mushroom music must my myself mystery myth
nail name nap narrow nasty nation national native natural nature navy near nearly neat necessary neck need needle negative neighbor neither nephew nerve nervous nest net network never new news newspaper next nice niece night nine no noble nobody nod noise none noon nor normal north nose not note nothing notice now nuclear number nurse nut
oak oar object ocean odd of off offer office officer official often oil okay old olive olympic on once one onion only onto open opera operate opinion opponent opportunity opposite or orange orbit order ordinary organ organize origin original other otherwise ought our ours ourselves out outdoor outer outline outside oven over owe own owner oxygen
pace pack package pad page paid pain paint pair palace pale palm pan pancake panel panic pants paper parade parent park part party pass passage passenger passport past pasta paste pastor pat path patient patrol pattern pause pay peace peach peak peanut pear peasant pen pencil penny people pepper per percent perfect perform perhaps period permit person pet phone photo piano pick picnic picture pie piece pig pile pill pillow pilot pin pine pink pioneer pipe pirate pit pitch pizza place plain plan plane planet plant plastic plate play player please pleasure plenty plot plow plug plus pocket poem poet point poison pole police policy polish polite political pond pool poor pop popular population porch pork port portion portrait position positive possess possible post pot potato pound pour powder power practice praise pray precious precise predict prefer prepare present president press pressure pretend pretty prevent price pride priest primary prince princess print prior prison private prize problem process produce product professional professor profit program progress project promise promote proof property protect protein proud prove provide public pull pump punch punish pupil puppy purchase pure purple purpose purse push put puzzle pyramid
queen question quick quiet quilt quit quite quote
rabbit race racial rack radio rail rain raise rally ranch random range rank rapid rare rate rather raw ray reach react read ready real reality realize really rear reason rebel recall receive recent recipe record recover red reduce refer reflect refrigerator refuse region regret regular reject relate relative relax release relief religion rely remain remember remind remote remove rent repair repeat replace reply report represent request require rescue research reserve resident resist resource respect respond rest restaurant result return reveal revenge review revolution reward rice rich rid ride ridge ridiculous right ring riot rip rise risk river road roar roast rob robot rock rocket rod role roll roman romance roof room root rope rose rough round route row royal rub rubber rude rug ruin rule ruler run rural rush rust
sack sad safe safety said sail salad salary sale salt same sample sand sandwich save say scale scan scare scarf scene school science scissors score scratch scream screen screw sea search season seat second secret section see seed seek seem seen select self sell send senior sense sentence separate series serious serve service session set settle seven several severe sew sex shade shadow shake shall shame shape share shark sharp shave she sheep sheet shelf shell shelter shift shine ship shirt shock shoe shoot shop shore short shot should shoulder shout show shower shut shy sick side sight sign signal silence silent silk silly silver similar simple simply since sing singer single sink sir sister sit site situation six size skill skin skip skirt sky slave sleep slice slide slight slip slope slow small smart smell smile smoke smooth snake snap snow so soap soccer social sock soda sofa soft soil solar soldier solid solve some somebody someone something sometimes son song soon sorry sort soul sound soup source south space spare speak speaker special speech speed spell spend spider spin spirit spit spite split spoil spoke spoon sport spot spray spread spring square squeeze stable staff stage stain stair stamp stand star stare start state station stay steak steal steam steel steep steer stem step stick still sting stir stock stomach stone stood stop store storm story stove straight strange stranger strategy straw stream street strength stress stretch strike string strip stroke strong structure struggle student study stuff stupid style subject subtract succeed success such sudden sugar suggest suit summer sun sunday super supply support suppose sure surface surprise surround survey survive swallow swamp swan swear sweat sweater sweep sweet swim swing switch sword symbol system
table tackle tail take tale talk tall tank tap tape target task taste tax taxi tea teach teacher team tear teaspoon tech teeth telephone television tell temperature temple ten tend tennis tent term terrible test text than thank that the theater their them theme themselves then theory there these they thick thief thin thing think third thirty this those though thought thousand thread threat three throat through throw thumb thunder thursday thus ticket tide tie tiger tight till time tin tiny tip tire tired title to toast today toe together toilet tomato tomorrow ton tone tongue tonight too took tool tooth top topic torch torn total touch tough tour toward towel tower town toy track trade traffic trail train transfer transport trap trash travel tray treasure treat tree trend trial tribe trick trip troop tropical trouble truck true truly trumpet trust truth try tube tuesday tune tunnel turkey turn turtle twelve twenty twice twin twist two type
ugly umbrella uncle under understand underwear unemployed unexpected unfortunately uniform union unique unit universe university unless until unusual up upon upper upset upside upstairs urban urge us use used useful usual usually
vacation vaccine valley valuable value van vanish various vary vast vegetable vehicle vein verb very vessel veteran via victim victory video view village vinegar violence violent violin virus visible vision visit visitor vitamin voice volcano volume volunteer vote vowel voyage
wage wagon wait wake walk wall wallet wander want war warm warn wash waste watch water wave wax way we weak wealth weapon wear weather web wedding Wednesday week weekend weigh weight weird welcome well went were west wet whale what wheat wheel when where whether which while whisper white who whole whom whose why wide wife wild will win wind window wine wing winter wipe wire wisdom wise wish wit with within without wolf woman women wonder wood wooden wool word work worker world worm worry worse worship worst worth would wound wrap wreck wrist write writer wrong wrote
yard yeah year yellow yes yesterday yet yield you young your yours yourself youth
zebra zero zone zoo zoom
`.trim().split(/\s+/).filter(w => w.length >= 3));

export const TRIVIA = {
    general: [
        { q: 'How many days are in a leap year?', opts: ['365', '366', '364', '360'], a: 1 },
        { q: 'What colour do you get mixing red and white?', opts: ['Pink', 'Purple', 'Orange', 'Brown'], a: 0 },
        { q: 'How many continents are there?', opts: ['5', '6', '7', '8'], a: 2 },
        { q: 'What is the largest ocean?', opts: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], a: 3 },
        { q: 'How many zeros in one million?', opts: ['5', '6', '7', '8'], a: 1 },
        { q: 'What language has the most native speakers?', opts: ['English', 'Mandarin Chinese', 'Spanish', 'Hindi'], a: 1 },
        { q: 'Which planet is known as the Red Planet?', opts: ['Venus', 'Mars', 'Jupiter', 'Mercury'], a: 1 },
        { q: 'How many minutes in a full day?', opts: ['1400', '1440', '1480', '1500'], a: 1 }
    ],
    science: [
        { q: 'What gas do plants absorb from the air?', opts: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], a: 2 },
        { q: 'What is H2O?', opts: ['Salt', 'Water', 'Acid', 'Air'], a: 1 },
        { q: 'How many bones in an adult human body?', opts: ['186', '206', '216', '256'], a: 1 },
        { q: 'What is the closest star to Earth?', opts: ['Sirius', 'The Sun', 'Polaris', 'Alpha Centauri'], a: 1 },
        { q: 'What boils at 100°C at sea level?', opts: ['Oil', 'Alcohol', 'Water', 'Mercury'], a: 2 },
        { q: 'Which blood cells fight infection?', opts: ['Red', 'White', 'Platelets', 'Plasma'], a: 1 },
        { q: 'What force pulls objects toward Earth?', opts: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], a: 2 },
        { q: 'DNA is found mainly in which part of a cell?', opts: ['Nucleus', 'Membrane', 'Cytoplasm', 'Ribosome'], a: 0 }
    ],
    history: [
        { q: 'Who was the first President of the USA?', opts: ['Lincoln', 'Jefferson', 'Washington', 'Adams'], a: 2 },
        { q: 'In which year did Nigeria gain independence?', opts: ['1957', '1960', '1963', '1966'], a: 1 },
        { q: 'The Great Wall is in which country?', opts: ['Japan', 'India', 'China', 'Korea'], a: 2 },
        { q: 'Who discovered the sea route to India from Europe?', opts: ['Columbus', 'Vasco da Gama', 'Magellan', 'Cook'], a: 1 },
        { q: 'World War II ended in which year?', opts: ['1943', '1944', '1945', '1946'], a: 2 },
        { q: 'Ancient pyramids of Giza are in?', opts: ['Mexico', 'Sudan', 'Egypt', 'Peru'], a: 2 },
        { q: 'Who painted the Mona Lisa?', opts: ['Michelangelo', 'Van Gogh', 'Picasso', 'Leonardo da Vinci'], a: 3 },
        { q: 'The Berlin Wall fell in?', opts: ['1987', '1989', '1991', '1993'], a: 1 }
    ],
    sports: [
        { q: 'How many players on a football (soccer) team on the pitch?', opts: ['9', '10', '11', '12'], a: 2 },
        { q: 'The Olympics are held every how many years?', opts: ['2', '3', '4', '5'], a: 2 },
        { q: 'Which country has won the most FIFA World Cups?', opts: ['Germany', 'Italy', 'Argentina', 'Brazil'], a: 3 },
        { q: 'A basketball hoop is how many feet high?', opts: ['8', '9', '10', '12'], a: 2 },
        { q: 'In tennis, 15-15 is called?', opts: ['Deuce', '15-all', 'Love-15', 'Advantage'], a: 1 },
        { q: 'How many rings on the Olympic flag?', opts: ['4', '5', '6', '7'], a: 1 },
        { q: 'Wimbledon is played on?', opts: ['Clay', 'Hard court', 'Grass', 'Carpet'], a: 2 },
        { q: 'A cricket Test match can last up to how many days?', opts: ['3', '4', '5', '7'], a: 2 }
    ],
    naija: [
        { q: 'What is the capital of Nigeria?', opts: ['Lagos', 'Abuja', 'Kano', 'Port Harcourt'], a: 1 },
        { q: 'How many states does Nigeria have?', opts: ['30', '36', '37', '42'], a: 1 },
        { q: 'Naira is divided into 100 what?', opts: ['Cents', 'Kobo', 'Pesewas', 'Shillings'], a: 1 },
        { q: 'Which Nigerian won the Nobel Prize in Literature?', opts: ['Chinua Achebe', 'Wole Soyinka', 'Chimamanda', 'Ben Okri'], a: 1 },
        { q: 'Nollywood is the film industry of?', opts: ['Ghana', 'Kenya', 'Nigeria', 'South Africa'], a: 2 },
        { q: 'The Niger River empties into the?', opts: ['Atlantic', 'Mediterranean', 'Indian Ocean', 'Red Sea'], a: 0 },
        { q: 'Which is NOT a Nigerian geopolitical zone?', opts: ['South-West', 'North-Central', 'Middle-Belt Zone', 'South-East'], a: 2 },
        { q: 'Jollof rice beef is most famously a rivalry between Nigeria and?', opts: ['Togo', 'Ghana', 'Benin', 'Cameroon'], a: 1 }
    ]
};

export const RIDDLES = [
    { q: 'What has keys but no locks, space but no room, and you can enter but not go inside?', a: ['keyboard'], hints: ['You type on it.', 'It sits in front of a computer.'] },
    { q: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?', a: ['echo'], hints: ['You hear me in mountains.', 'I repeat what you say.'] },
    { q: 'The more you take, the more you leave behind. What are they?', a: ['footsteps', 'steps', 'footstep'], hints: ['You make them when you walk.', 'They are behind you on a path.'] },
    { q: 'What can travel around the world while staying in a corner?', a: ['stamp', 'postage stamp'], hints: ['It goes on an envelope.', 'It costs a few naira or cents.'] },
    { q: 'What has a head and a tail but no body?', a: ['coin', 'a coin'], hints: ['You flip it.', 'Money.'] },
    { q: 'What gets wetter the more it dries?', a: ['towel'], hints: ['You use it after a bath.', 'It hangs in the bathroom.'] },
    { q: 'I have cities, but no houses. Forests, but no trees. Water, but no fish. What am I?', a: ['map'], hints: ['You fold me.', 'I help you find places.'] },
    { q: 'What has to be broken before you can use it?', a: ['egg'], hints: ['Breakfast.', 'It has a shell.'] },
    { q: 'What goes up but never comes down?', a: ['age'], hints: ['It only increases.', 'Birthday related.'] },
    { q: 'I am tall when I am young, and short when I am old. What am I?', a: ['candle'], hints: ['I melt.', 'I give light.'] },
    { q: 'What has hands but cannot clap?', a: ['clock', 'watch'], hints: ['It tells time.', 'Twelve of something.'] },
    { q: 'What invention lets you look through a wall?', a: ['window'], hints: ['Glass.', 'In every house.'] },
    { q: 'The more of this there is, the less you see. What is it?', a: ['darkness', 'dark', 'night'], hints: ['Opposite of light.', 'You need a torch.'] },
    { q: 'What has one eye but cannot see?', a: ['needle'], hints: ['Used for sewing.', 'Thread goes through it.'] },
    { q: 'What kind of band never plays music?', a: ['rubber band', 'rubberband'], hints: ['It stretches.', 'It holds things together.'] },
    { q: 'What can you catch but not throw?', a: ['cold', 'a cold'], hints: ['You get sick.', 'Sneezing.'] },
    { q: 'What has a neck but no head?', a: ['bottle'], hints: ['You drink from it.', 'Glass or plastic.'] },
    { q: 'If you drop me I am sure to crack, but give me a smile and I will always smile back. What am I?', a: ['mirror'], hints: ['You look at yourself.', 'On the wall.'] },
    { q: 'What building has the most stories?', a: ['library'], hints: ['Books.', 'Quiet please.'] },
    { q: 'What runs but never walks, has a bed but never sleeps?', a: ['river'], hints: ['Water.', 'It has a mouth too.'] }
];
